### ISSUE TITLE
All unit test failed 

### ISSUE THREAD

**Issue by kbarbora** [EQuiw/code-imitator#1]
Hi, whenver I run the python test testFeatureExtractionv2.py and test_learningv2.py I get error in the function assertAlmostEqual, what I did, I lowered the precision so they passed.
Will that affect in the regular execution?

Thank you.

**Comment by EQuiw** [comment]
Thank you very much for the hint.
Indeed, the clang-based features slightly depend on the system, so some features will include the setup of your system. Such features should be removed after the feature selection (at least, in my case, there were not present anymore). That's why it is always important to look at the features, e.g. by using `getcolnames()`. Some minor variation should thus not be a big issue, but of course, it is hard to tell.

I will redesign the tests to consider that (or publish the feature files to test the extraction directly).
Thanks again.
